### ISSUE TITLE
Bundling failed

### ISSUE THREAD

**Issue by LionelCremer** [marudy/react-native-responsive-screen#9]
error: bundling failed: Error: While trying to resolve module `react-native-responsive-screen` from file `/Users/lionelcremer/WebstormProjects/first_app_demo/App.js`, the package `/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/react-native-responsive-screen/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/react-native-responsive-screen/index.js`. Indeed, none of these files exist:

  * `/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/react-native-responsive-screen/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/react-native-responsive-screen/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:15)
    at DependencyGraph.resolveDependency (/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
    at /Users/lionelcremer/WebstormProjects/first_app_demo/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:467
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by marudy** [comment]
Hi there,

Just a quick tip: did you try to restart the JavaScript server when you installed the package? It looks like metro bundler cannot find the index.js file but it exists in the package.

If you are still experiencing the issue do you have this repository of yours public? I can use it to try reproduce the issue :)

**Comment by marudy** [comment]
Hi @LionelCremer,

any updates on this one? I'm here to help, just let me know the specifics :)

**Comment by marudy** [comment]
No worries, thanks for the update!
